### ISSUE TITLE
Footer element

### ISSUE THREAD

**Issue by luiscmartinez** [elac-huskies-computer-club/huskies-club-site#6]
Use [DaisyUI Footer component](https://daisyui.com/components/footer/#footer-with-copyright-text-and-social-icons).

steps:
1. Change background color
2. Put in the social icons
3. Add text

![Untitled](https://github.com/elac-huskies-computer-club/huskies-club-site/assets/36746854/158d14ff-4a0b-44d1-a3d5-753351de6d58)

time effort - lvl 1

**Comment by AngelinCS** [comment]
Got it
